apiVersion: v1
kind: Service
metadata:
  name: <service-name>
spec:
  selector:
    app: <service-name>
  type: NodePort
  ports:
  - name: notebook
    port: <service port number you want to map to>
    targetPort: <container port number>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <app-name>
spec:
  selector:
    matchLabels:
      app: <app-name>
  replicas: 1
  template:
    metadata:
      labels:
        app: <app-name>
    spec:
      containers:
      - name: <container name>
        image: <image name>
        ports:
        - containerPort: <container port number>
        imagePullPolicy: Never           